"""added death_report table and updated family_member table 

Revision ID: 26cf216b8765
Revises: 82d13eedf207
Create Date: 2026-07-07 04:31:31.883604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cf216b8765'
down_revision: Union[str, Sequence[str], None] = '82d13eedf207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('death_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_family_id', sa.UUID(), nullable=True),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['institution_staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_family_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('family_members_user_id_key'), 'family_members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('family_members_user_id_key'), 'family_members', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('death_reports')
    # ### end Alembic commands ###
