"""add certificate number to certificate

Revision ID: 72b867c1680f
Revises: e809ff398be8
Create Date: 2026-07-06 04:01:06.804256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b867c1680f'
down_revision: Union[str, Sequence[str], None] = 'e809ff398be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('certificate_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'certificates', ['certificate_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificates', type_='unique')
    op.drop_column('certificates', 'certificate_number')
    # ### end Alembic commands ###
