"""updated family_member table

Revision ID: 82d13eedf207
Revises: 72b867c1680f
Create Date: 2026-07-07 01:53:18.907308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d13eedf207'
down_revision: Union[str, Sequence[str], None] = '72b867c1680f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('family_members', 'full_name')
    op.drop_column('family_members', 'email')
    op.drop_column('family_members', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('family_members', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('family_members', sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('family_members', 'created_at')
    # ### end Alembic commands ###
