"""update donor consent schema

Revision ID: ac191e09e2f7
Revises: 87bd072568f3
Create Date: 2026-06-20 12:41:31.171905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac191e09e2f7'
down_revision: Union[str, Sequence[str], None] = '87bd072568f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_witnesses', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('consent_witnesses', sa.Column('verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'consent_witnesses', ['verification_token'])
    op.create_unique_constraint(None, 'consents', ['donor_id'])
    op.add_column('donors', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('donors', sa.Column('middle_name', sa.String(length=50), nullable=True))
    op.add_column('donors', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('donors', sa.Column('parent_name', sa.String(length=100), nullable=False))
    op.add_column('donors', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('donors', sa.Column('address_line_1', sa.String(length=255), nullable=False))
    op.add_column('donors', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('donors', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('donors', sa.Column('identity_type', sa.String(length=50), nullable=False))
    op.add_column('donors', sa.Column('identity_number', sa.String(length=100), nullable=False))
    op.add_column('donors', sa.Column('declaration_accepted', sa.Boolean(), nullable=False))
    op.alter_column('donors', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('donors', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('donors', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('donors', 'declaration_accepted')
    op.drop_column('donors', 'identity_number')
    op.drop_column('donors', 'identity_type')
    op.drop_column('donors', 'district')
    op.drop_column('donors', 'address_line_2')
    op.drop_column('donors', 'address_line_1')
    op.drop_column('donors', 'occupation')
    op.drop_column('donors', 'parent_name')
    op.drop_column('donors', 'last_name')
    op.drop_column('donors', 'middle_name')
    op.drop_column('donors', 'first_name')
    op.drop_constraint(None, 'consents', type_='unique')
    op.drop_constraint(None, 'consent_witnesses', type_='unique')
    op.drop_column('consent_witnesses', 'verification_sent_at')
    op.drop_column('consent_witnesses', 'verification_token')
    # ### end Alembic commands ###
