"""add cadaver model

Revision ID: e1259a7eaf83
Revises: 26cf216b8765
Create Date: 2026-08-09 22:02:35.930918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1259a7eaf83'
down_revision: Union[str, Sequence[str], None] = '26cf216b8765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadavers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['institution_staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['institution_staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('death_reports', sa.Column('assigned_admin_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('death_reports_assigned_staff_id_fkey'), 'death_reports', type_='foreignkey')
    op.create_foreign_key(None, 'death_reports', 'institution_staff', ['assigned_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('death_reports', 'assigned_staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_reports', sa.Column('assigned_staff_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'death_reports', type_='foreignkey')
    op.create_foreign_key(op.f('death_reports_assigned_staff_id_fkey'), 'death_reports', 'institution_staff', ['assigned_staff_id'], ['id'], ondelete='SET NULL')
    op.drop_column('death_reports', 'assigned_admin_id')
    op.drop_table('cadavers')
    # ### end Alembic commands ###
