"""remove occupation from donor

Revision ID: e809ff398be8
Revises: ac191e09e2f7
Create Date: 2026-06-20 15:58:53.471250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e809ff398be8'
down_revision: Union[str, Sequence[str], None] = 'ac191e09e2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
