"""update cadaver model

Revision ID: f0a1efe8d57c
Revises: 4357e7b88e15
Create Date: 2026-08-09 23:46:28.777210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a1efe8d57c'
down_revision: Union[str, Sequence[str], None] = '4357e7b88e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadavers', sa.Column('family_member_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('cadavers_assigned_staff_id_fkey'), 'cadavers', type_='foreignkey')
    op.create_foreign_key(None, 'cadavers', 'family_members', ['family_member_id'], ['id'], ondelete='SET NULL')
    op.drop_column('cadavers', 'assigned_staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadavers', sa.Column('assigned_staff_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cadavers', type_='foreignkey')
    op.create_foreign_key(op.f('cadavers_assigned_staff_id_fkey'), 'cadavers', 'institution_staff', ['assigned_staff_id'], ['id'], ondelete='SET NULL')
    op.drop_column('cadavers', 'family_member_id')
    # ### end Alembic commands ###
